require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RequestsController do

  def mock_request(stubs={})
    @mock_request ||= mock_model(Request, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all requests as @requests" do
      Request.stub(:top_ten) { [mock_request] }
      get :index
      assigns(:requests).should eq([mock_request])
    end
    
    it "search_results should not return songs if params blank" do
      Request.stub(:search_result).and_return('')
      get 'index', :song => ''
      Request.search_result.should == ''
    end
    
    it "search_results should return songs if params not blank" do
      Request.stub(:search_result).and_return('One')
      get 'index', :song => 'One'
      Request.search_result.should == 'One'
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created request as @request" do
        Request.stub(:new) { mock_request(:save => true) }
        post :create, :request => {}
        assigns(:request).should be(mock_request)
      end

      it "redirects to the created request" do
        Request.stub(:new) { mock_request(:save => true) }
        post :create, :request => {}
        response.should redirect_to(requests_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved request as @request" do
        Request.stub(:new) { mock_request(:save_or_update => false) }
        post :create, :request => {}
        assigns(:request).should be(mock_request)
      end

      it "re-renders the 'index' template" do
        Request.stub(:new) { mock_request(:save => false) }
        post :create, :request => {}
        response.should redirect_to(requests_path)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested request" do
      Request.stub(:find).with("37") { mock_request }
      mock_request.should_receive(:subtract_point)
      delete :destroy, :id => "37"
    end

    it "redirects to the requests list" do
      Request.stub(:find) { mock_request }
      delete :destroy, :id => "1"
      response.should redirect_to(requests_url)
    end
  end

end
